apiVersion: v1
kind: Pod
metadata:
  name: todo-app
spec:
  containers:
  - name: todo-app
    image: https://129390742221.dkr.ecr.us-west-2.amazonaws.com:latest
    ports:
    - containerPort: 8000

